server: #Cấu hình cho máy chủ web nhúng được sử dụng bởi Spring Boot
  port: 8090
  servlet: #Cấu hình cho Servlet, một phần quan trọng của máy chủ web Java
    context-path: /identity # Định nghĩa đường dẫn context mà ứng dụng sẽ được triển khai trên máy chủ. Ở đây, nó là /identity

spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: webbanhang
#Cung cấp cấu hình cho việc sử dụng JPA (Java Persistence API) trong ứng dụng
  jpa:
    hibernate: #Cấu hình cho Hibernate, một trong những triển khai của JPA
      ddl-auto: update # Xác định cách Hibernate tạo bảng trong cơ sở dữ liệu. Ở đây, nó được đặt là update, có nghĩa là Hibernate sẽ tự động cập nhật cấu trúc bảng nếu cần
    database-platform: org.hibernate.dialect.MySQLDialect #Chỉ định loại cơ sở dữ liệu mà Hibernate sử dụng
    generate-ddl: true # Xác định xem Hibernate có nên sinh ra các câu lệnh tạo bảng SQL không. Ở đây, nó được đặt là true.
    show-sql: true # Chỉ định xem Hibernate có nên hiển thị các câu lệnh SQL mà nó tạo ra hay không. Ở đây, nó được đặt là true
    properties:
      hibernate:
        format_sql: true
  datasource: #  Cung cấp cấu hình cho nguồn dữ liệu (database) mà ứng dụng sử dụng
    driver-class-name: com.mysql.cj.jdbc.Driver # Chỉ định tên lớp driver JDBC được sử dụng để kết nối với cơ sở dữ liệu. Ở đây, nó là com.mysql.cj.jdbc.Driver.
    url: jdbc:mysql://localhost:3306/webbanhang?createDatabaseIfNotExist=true # Chứa URL kết nối đến cơ sở dữ liệu MySQL
    username: root
    password: 0903075545

jwt:
  signerKey: "Vabsn1UFPMGt9i0mKDaqRU2NdNwEw+VIZg8/Qa+37L521P1gqO4bRBEJyem2R7Zy"
  valid-duration: 18000 # in second
  refreshable-duration: 18000 # in seconds

administrator:
  password: 0903075546Vu!

email:
  password: gmsc erhf egck ecq

mail:
  host: smtp.gmail.com
  port: 587
  username: hoangvu.startwork@gmail.com
  password: gmsc erhf egck ecqd # cbuvybhourxuqnna
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
